#include "findMinimumIndex.h"
#include <iostream>
#include <algorithm>
#include <random>

/*
 * Alignment of  64 bytes
 */
constexpr int alignment = 64;
/*
 * create global data
 * a bit hacky way
 */
constexpr size_t n = 16 << 8;
float* array;
class InitArray
{
public:
  InitArray()
  {
    std::mt19937 gen;
    std::uniform_real_distribution<> dis(0.1, 100.0);
    // create buffer of right size,properly aligned
    size_t const size = n * sizeof(float);
    posix_memalign((void**)&array, alignment, size);
    for (size_t i = 0; i < n; ++i) {
      // Use dis to transform the random unsigned int generated by gen into a
      // double. Each call to dis(gen) generates a new random double
      array[i] = dis(gen);
    }
  }
  ~InitArray() { free(array); }
};
InitArray initArray;

/*
 * Scalar code kind of C style
 */
static void
findMinimumIndexC()
{
  int32_t minIndex = findMinIndexC(array, n);
  std::cout << "C Minimum index : " << minIndex << " with value "
            << array[minIndex] << '\n';
}

static void
findMinimumIndexC2()
{
  int32_t minIndex = findMinIndexC2(array, n);
  std::cout << "C2 Minimum index : " << minIndex << " with value "
            << array[minIndex] << '\n';
}

/*
 * Scalar code using STL
 */
static void
findMinimumIndexSTL()
{
  int32_t minIndex = findMinIndexSTL(array, n);
  std::cout << "STL Minimum index : " << minIndex << " with value "
            << array[minIndex] << '\n';
}
static void
findMinimumIndexVec()
{
  int32_t minIndex = findMinIndexVec(array, n);
  std::cout << "Vec Minimum index : " << minIndex << " with value " << array[minIndex]
            << '\n';
}
static void
findMinimumIndexVec16()
{
  int32_t minIndex = findMinIndexVec16(array, n);
  std::cout << "Vec Minimum index : " << minIndex << " with value " << array[minIndex]
            << '\n';
}


int main()
{
  findMinimumIndexC();
  findMinimumIndexC2();
  findMinimumIndexSTL();
  findMinimumIndexVec();
  findMinimumIndexVec16();
  return 0;
}
