#include "findMinimumIndex.h"
#include <algorithm>
#include <iostream>
#include <random>

/*
 * Alignment of  64 bytes
 */
constexpr int alignment = 64;
/*
 * create global data
 * a bit hacky way
 */
constexpr size_t n = 16 << 8;
float* array;
class InitArray
{
public:
  InitArray()
  {
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_real_distribution<> dis(0.1, 100.0);
    // create buffer of right size,properly aligned
    size_t const size = n * sizeof(float);
    posix_memalign((void**)&array, alignment, size);
    for (size_t i = 0; i < n; ++i) {
      // Use dis to transform the random unsigned int generated by gen into a
      // double. Each call to dis(gen) generates a new random double
      array[i] = dis(gen);
    }
  }
  ~InitArray() { free(array); }
};
InitArray initArray;

static void
findMinimumIndexC()
{
  int32_t minIndex = findMinIndexC(array, n);
  std::cout << "C Minimum index : " << minIndex << " with value "
            << array[minIndex] << '\n';
}

static void
findMinimumIndexSTL()
{
  int32_t minIndex = findMinIndexSTL(array, n);
  std::cout << "STL Minimum index : " << minIndex << " with value "
            << array[minIndex] << '\n';
}

/*
 * vec find the minimum and index (impl 1)
 */
static void
findMinimumIndexVec()
{
  int32_t minIndex = findMinIndexVec(array, n);
  std::cout << "Vec Minimum index 1 : " << minIndex << " with value "
            << array[minIndex] << '\n';
}

/*
 * vec find the minimum and index (impl 2)
 */
static void
findMinimumIndexVec2()
{
  int32_t minIndex = findMinIndexVec2(array, n);
  std::cout << "Vec Minimum index 2 : " << minIndex << " with value "
            << array[minIndex] << '\n';
}

int
main()
{
  findMinimumIndexC();
  findMinimumIndexSTL();
  findMinimumIndexVec();
  findMinimumIndexVec2();
  return 0;
}
